### ISSUE TITLE
支払い方法変更を指定してバリデーションエラー発生時に、システムエラーとなる

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/sample-payment-plugin#31]
## 前提
   サンプル決済プラグインをインストール済み。
   注文手続き画面のテンプレートに{{ form_widget(form.sample_payment_token) }}を追記済み。

## 操作
   注文手続き画面で例えば「代金引換」を選ぶ。
   ↓
   フォームに異常値を入力する。例えば「お問い合わせ」に3001文字を入力する。
   ↓
   支払い方法で「サンプル決済(トークン)」を選択する。
   ↓
   システムエラー

## 原因
   バリデーションエラーが発生しているためShoppingController::redirectToでリダイレクトが発生しない。
   そのため、フォームに「sample_payment_token」がaddされない。
   でも$Orderの決済手段は「サンプル決済(トークン)」になっているため、twigでHTMLを生成する際に
   form_widget(form.sample_payment_token)
   がコールされ、存在しない項目のためエラーとなる。
   解決策として、バリデーションエラー時は$Orderの決済手段を変更前のものに戻す必要がある？

以下、 Slack からの問い合わせより

https://ec-cube.slack.com/archives/C03P2Q8QL/p1542689928025300

**Comment by nanasess** [comment]
以下のように、常に追加フォームを表示させておくことで改善されないか。

https://github.com/nanasess/sample-payment-plugin/commit/66c13a30b99b7f7a6e5c220bcd049921d2c23de4

**Comment by chihiro-adachi** [comment]
#32 で修正
